kodeaberne/circularlab

README.md
=> docs(README): edit readme

README.md
=> docs(readme): add install instructions

src/layouts/BaseLayout.astro
Created BaseLayout and empty components for header and footer.
=> feat(BaseLayout): create BaseLayout

src/components/Quote.astro, src/pages/index.astro, src/styles/color.css
Added quote section to landing page.
=> feat(Quote): add Quote section

src/pages/events.astro
Added events page with dynamic fetching of data.
=> feat(events): add events page

src/components/Card.astro, src/components/Footer.astro, src/images/plus.svg, src/layouts/BaseLayout.astro, src/pages/events.astro, src/pages/single.astro
Added dynamic single event view.
=> feat(single): add single event view

src/components/Card.astro, src/components/Header.astro
=> fix(links): fix links to event and single

src/pages/dashboard.astro, src/pages/single.astro
=> feat(dashboard): change categories on dashboard

src/styles/color.css
changed the color to the correct hex
=> feat(change color)

src/components/Header.astro
=> feat(add pointer)

src/components/Header.astro, src/layouts/BaseLayout.astro
Added auto hide animation to the navbar.
=> feat(menu): add menu auto hide animation

src/pages/signin.astro
=> feat(style login page)

src/components/Card.astro, src/pages/events.astro
Added new design to event view.
=> feat(events): add new design to events

src/components/Hero.astro
=> feat(hero): change hero to new design

src/components/Button.astro, src/pages/events.astro
Added buttons to events page, and gave button component a fixed width.
=> feat(events): add buttons to eventpage

src/components/Footer.astro, src/layouts/BaseLayout.astro
=> feat(main): change max-width on main

src/pages/index.astro
=> fix(index): fix index layout

src/pages/events.astro
=> fix(events): fix event images

src/components/About.astro, src/components/Header.astro, src/pages/index.astro
jeg endret instagram og fikk "om cirkulær lab" til å funke, men når man er inne på index siden lukker ikke burger menyen seg når man klikker på den... ante ikke hvordan jeg skulle fixe det, vet ikke om det kanskje var noe med js :pp
=> bug(changed the links in meny)

src/components/Header.astro
=> fix(header): align logo center

src/components/About.astro, src/components/Ansvar.astro, src/components/HvadEr.astro, src/components/MaterialLab.astro, src/styles/fonts.css
Fixes kod-149.
- set p max width: 60ch.
- set font sizes
- changes h1 to h2 for better accessibility.
=> fix(fonts): fix paragraph width

src/components/Card.astro, src/components/Events.astro, src/pages/index.astro
Added events section to landing page.
=> feat(Events): Add events section to landing page

src/components/Ansvar.astro, src/pages/index.astro
Updated the Ansvar component to its new design, and added an embed for video.
=> feat(Ansvar): update Ansvar to new design

src/components/Instagram.astro, src/pages/index.astro
=> feat(Instagram): fix Instagram desktop width

src/components/Footer.astro
=> fix(Footer): fix footer sizing

src/components/About.astro, src/components/Button.astro, src/components/Circular.astro, src/components/Hero.astro
Added button links and hover animation.
=> feat(Button): add button links

src/components/Footer.astro
Fixed footer some link to instagram.
=> fix(some): fix some links

src/pages/single.astro
=> fix(single): fix line height

src/layouts/BaseLayout.astro
Added meta description for better SEO.
=> feat(meta): add meta description

src/components/Circular.astro
=> fix(circular): fix paragraf bug

src/components/About.astro, src/components/Ansvar.astro, src/components/MaterialLab.astro
Fixed the padding for desktop view.
=> fix(layout): fix padding for text on desktop

src/components/Ansvar.astro, src/components/Circular.astro, src/components/MaterialLab.astro, src/images/plus.svg, src/pages/index.astro
=> fix(layout): change layout

src/components/Ansvar.astro
=> fix(Ansvar): fix video size on chrome

src/components/About.astro, src/components/Ansvar.astro, src/components/Circular.astro, src/components/MaterialLab.astro
=> fix(text-alignment): fix text-alignment

src/components/Hero.astro
=> fix(Hero): fix Hero padding mobile

src/components/Ansvar.astro
Replaced paragraf text with new copy.
=> feat(Ansvar): replace text
